[package]
name = "xtask"
version = "0.1.1"
edition = "2024"
publish = false

[dependencies]
anyhow = "1.0"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "rustls-tls"] }
sha2 = "0.10"
